services:
  - type: static
    name: kakeibo-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://kakeibobackend-t7v7.onrender.com"
    autoDeploy: true
    routes:
      - path: "/*"
        destination: "/index.html"
        status: 200
